### ISSUE TITLE
Minimising Downtime with Migrations

### ISSUE THREAD

**Issue by gryevns** [edgarroman/zappa-django-guide#12]
Great guide - thanks!

Currently under the "Init the Database" section, the guide says:
> And repeat this process every time you make model changes.

If I add a new column to a model/table does this mean until I execute `zappa manage dev migrate` there will be downtime? If so how can I minimise downtime - can I run migrations without deploying new application logic?

**Comment by edgarroman** [comment]
You have to run locally:
`python manage.py makemigrations`
`zappa update dev`
To get the migration files to the zappa instance in Lambda, then
run 
`zappa manage dev migrate` to actually migrate.

Due to the nature of Django, the migration scripts are backward compatible so if you update the database before you push the column changes in your model, there will be no downtime.
