### ISSUE TITLE
Django 1.10 -> 3.1.8+

### ISSUE THREAD

**Issue by mslinn** [edgarroman/zappa-django-guide#41]
I just found this project, `zappa-django-guide`. So exciting!

Django 3.1.8 is current, but [the docs](https://romandc.com/zappa-django-guide/setup/#baseline-packages) for `zappa-django-guide` call for Django 1.10. It is unclear if this is merely over-specification, or there is a technical reason why such an old version is named as a requirement.

PS, unrelated, but I also see `Copyright © 2016 - 2017 Edgar Roman ` at the bottom of each page. Unless Mr. Roman completely stopped contributing 4 years ago, the end year should probably be updated.

**Comment by edgarroman** [comment]
Hi @mslinn - thanks for the feedback.  The good news is that not much has fundamentally changed from the overall process, but the services and packages have marched forward.  Certainly most notable is Django is now **way** beyond 1.10, but it still works!

And coincidentally, I am working on an entire new version of this documentation, albeit as a paid course.  The new version will address the small changes and new versions.  

But I will address the Copyright notice

**Comment by mslinn** [comment]
I am very much in learning mode. Just came across a reference to [Zappa.io, which is dead](https://www.reddit.com/r/django/comments/jcrdjg/serverless_deployment_of_a_django_project_with/). 

[This comment](https://www.reddit.com/r/django/comments/jcrdjg/serverless_deployment_of_a_django_project_with/g94wmmc) made me wonder if serverless is better than a supposedly dying Zappa, or whether he was blowing smoke.

**Comment by edgarroman** [comment]
The Zappa project is currently suffering from lack of dedicated maintainers and is a at tipping point - if additional maintainers can be recruited, then it can flourish.  The reason zappa.io is dead is because it's moving to a generic github account instead of a personal account.  I hope it can be sorted out in the next few months because the project is truly awesome!  For more interactive communication, consider joining the zappa slack: https://zappateam.slack.com/

**Comment by mslinn** [comment]
The question that comes to mind is: what are the pros and cons of using Zappa vs Serverless for Django projects? A second (and third) opinion would be helpful.

**Comment by edgarroman** [comment]
Purely my opinion: I have stayed away from Serverless because:
1. In the past, they were treating Python like a 2nd tier language - that may have changed
2. Serverless is skewing toward a commercial service and that makes me a little nervous for personal projects, but maybe it's ok for companies.

Ultimately if you're using simple Django, then Zappa is the winner hands down, but if you're using some other framework or have more complex infrastructure, then you may want to investigate Serverless.

**Comment by mslinn** [comment]
Thanks for the information. [I am only interested in Django webapps](https://www.mslinn.com/django/index.html), specifically Django-Oscar webapps. Being subject to a VC-backed startup's need for financial results is not desirable for me. I will look for more info on this.

**Comment by edgarroman** [comment]
One more comment as we discussed before closing this issue: serverless requires that you create an account and you cannot deploy updates if their servers are down.  Zappa is standalone, requires no account, and builds and pushes from your local machine.
