### ISSUE TITLE
Using a CDN for the entire project

### ISSUE THREAD

**Issue by mslinn** [edgarroman/zappa-django-guide#42]
The `zappa-django-guide` [docs say](https://romandc.com/zappa-django-guide/walk_static/#using-a-cdn-for-the-entire-project):

> There are also advantages to serving the entire Django project (Lambda functions and S3 Static files) via the CloudFront CDN. This option will not be covered in this Walkthrough.

Sounds like [Lambda@Edge](https://aws.amazon.com/lambda/edge/). OMG. Please. Tell. Me. More!

**Comment by edgarroman** [comment]
Two different things: 

- For a mostly non-interactive Django site, you may put any CDN in front of the Zappa project in order to have responses cached in a pretty typical fashion.  

- For true distributed interaction, you'll want to experiment with the `endpoint_configuration` option in your `zappa_settings.json` file - specifically use the `EDGE` option.  It's a very wonderful configuration to really take advantage of CloudFront's distributed footprint.  It's been a while since I last use that configuration, but I recall that deployments take much longer due to how cloudfront pushes out the code - this may have changed.
