### ISSUE TITLE
docker-lambda Python 3.6 image has sqlite3 dependency issue

### ISSUE THREAD

**Issue by moniquemurphy** [edgarroman/zappa-django-guide#9]
This is really more of a docker-lambda issue, but the tutorial might want to address it. 

See [this open issue from docker-lambda](https://github.com/lambci/docker-lambda/issues/36). `python manage.py runserver` in Core Django setup runs into this _sqlite3 import error and server cannot be run. 

`yum install sqlite-devel` inside the Docker container does not fix the issue.

**Comment by edgarroman** [comment]
Yes, I was aware of this issue when I was writing a blog post about using the docker environment with python 3.  I had thought that it's not a big issue since I figured: "who would use sqlite with zappa anyway?"  Well, since I last updated that page we have a potentially realistic scenario:

[https://blog.zappa.io/posts/s3sqlite-a-serverless-relational-database](https://blog.zappa.io/posts/s3sqlite-a-serverless-relational-database)

I will see if I can add a temporary note that I can remove when this is (hopefully) resolved.
